# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\"\x1b\n\rEntityRequest\x12\n\n\x02id\x18\x01 \x01(\t\"?\n\x0e\x45ntityResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t2=\n\x0b\x46\x61stApiGrpc\x12.\n\tGetRecord\x12\x0e.EntityRequest\x1a\x0f.EntityResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_ENTITYREQUEST']._serialized_start=17
  _globals['_ENTITYREQUEST']._serialized_end=44
  _globals['_ENTITYRESPONSE']._serialized_start=46
  _globals['_ENTITYRESPONSE']._serialized_end=109
  _globals['_FASTAPIGRPC']._serialized_start=111
  _globals['_FASTAPIGRPC']._serialized_end=172
# @@protoc_insertion_point(module_scope)
