# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\",\n\x05Point\x12\x10\n\x08latitude\x18\x01 \x01(\x05\x12\x11\n\tlongitude\x18\x02 \x01(\x05\"\x0b\n\tRectangle\"1\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x18\n\x08location\x18\x02 \x01(\x0b\x32\x06.Point\"\x0e\n\x0cRouteSummary\"\x0b\n\tRouteNote2\xad\x01\n\nRouteGuide\x12 \n\nGetFeature\x12\x06.Point\x1a\x08.Feature\"\x00\x12(\n\x0cListFeatures\x12\n.Rectangle\x1a\x08.Feature\"\x00\x30\x01\x12(\n\x0bRecordRoute\x12\x06.Point\x1a\r.RouteSummary\"\x00(\x01\x12)\n\tRouteChat\x12\n.RouteNote\x1a\n.RouteNote\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_POINT']._serialized_start=17
  _globals['_POINT']._serialized_end=61
  _globals['_RECTANGLE']._serialized_start=63
  _globals['_RECTANGLE']._serialized_end=74
  _globals['_FEATURE']._serialized_start=76
  _globals['_FEATURE']._serialized_end=125
  _globals['_ROUTESUMMARY']._serialized_start=127
  _globals['_ROUTESUMMARY']._serialized_end=141
  _globals['_ROUTENOTE']._serialized_start=143
  _globals['_ROUTENOTE']._serialized_end=154
  _globals['_ROUTEGUIDE']._serialized_start=157
  _globals['_ROUTEGUIDE']._serialized_end=330
# @@protoc_insertion_point(module_scope)
